name: TheTestRoom

run-name: 0.0.2.${{ github.run_number }}

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
    branches:
    - main

env:
  _IS_BUILD_CANARY: false
  _IS_GITHUB_RELEASE: false
  _RELEASE_NAME: TheTestRoom
  _RELEASE_VERSION: v0
  _BUILD_BRANCH: "${{ github.ref }}"
  _BUILD_VERSION: "0.0.2.${{ github.run_number }}"
  # GIT: Fix reporting from stderr to stdout
  GIT_REDIRECT_STDERR: 2>&1

jobs:
  CICD:
    runs-on: windows-latest
    timeout-minutes: 1440
    strategy:
      max-parallel: 1
    steps:
    - name: Set Git Config
      run: |
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global core.longpaths true
    - name: Install iroga from crates.io
      uses: baptiste0928/cargo-install@v3
      with:
        crate: iroga
        version: 0.1.2
    - name: Install xmlint
      uses: baptiste0928/cargo-install@v3
      with:
        crate: xmllint
        git: https://github.com/dotaxis/xmllint
        commit: c28b413d3f9c73a3a343523e9a806962b56b1d1d
    - name: Checkout
      uses: actions/checkout@v4.1.0
    - name: Prepare Env
      run: ".github/workflows/prepare.ps1"
      shell: pwsh
    - name: Publish Canary release
      uses: ncipollo/release-action@v1
      if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'true' && success()
      with:
        artifacts: ".dist/*.iro"
        allowUpdates: true
        generateReleaseNotes: true
        prerelease: true
        removeArtifacts: true
        tag: canary
        name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}"
        body: |
          This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
    - name: Publish Stable release
      uses: ncipollo/release-action@v1
      if: env._IS_GITHUB_RELEASE == 'true' && env._IS_BUILD_CANARY == 'false' && success()
      with:
        artifacts: ".dist/*.iro"
        generateReleaseNotes: true
        makeLatest: true
        removeArtifacts: true
        name: "${{ env._RELEASE_NAME }}-${{ env._RELEASE_VERSION }}"
